### ISSUE TITLE
vdr-sc    2 smartcards with sams CAID issue

### ISSUE THREAD

**Issue by enigma131** [3PO/vdr-plugin-sc#1]
When using 2 smartcards with same CAID, vdr-sc  can't work on second card.

In file system-common.c, function cSystemScCore::ProcessECM :
*card=smartcards.LockCard(scId); calls function in smarcard.c with takes the first card with matching scId.

The problem here is that if there is no matching ecm->provId on card, the routine diden't look for second card ..
Here code must be done for looking on each card for matching provId before selecting it and call function Decode

**Comment by 3PO** [comment]
-> see the override.conf
