### ISSUE TITLE
VDR-2.4.0

### ISSUE THREAD

**Issue by cinfo2019** [3PO/vdr-plugin-sc#3]
ist es möglich das SC-Plugin an den VDR-2.4.0 anzupassen?

**Comment by knedlyk** [comment]
@cinfo2019 Please take a look at https://aur.archlinux.org/packages/vdr-sc/

**Comment by 3PO** [comment]
Erledigt!

Sollte nun wieder bauen.
Getestet habe ich es allerdings nicht, da ich das Plugin schon seit vielen Jahren nicht mehr verwende.
Du kannst ja eine Rückmeldung geben, ob es geht.

**Comment by cinfo2019** [comment]
es baut hier und spricht auch mit dem mcli — super danke

**Comment by 3PO** [comment]
OK, dann kann die issue ja geschlossen werden.
